#!/bin/ash
#
# entrypoint: Located at `/etc/container/entrypoint` this script is the custom
#             entry for a container as called by `/usr/bin/container-entrypoint` set
#             in the upstream [alpine-container](https://github.com/gautada/alpine-container).
#             The default template is kept in
#             [gist](https://gist.github.com/gautada/f185700af585a50b3884ad10c2b02f98)


container_version() {
 /bin/cat /etc/alpine-release
}

container_entrypoint() {
 cd /opt/uptime-kuma
 if [ -f "/mnt/volumes/container/kuma.db~" ] ; then
  /usr/bin/unstash-data
 fi
 # /usr/bin/node server/server.js --port=8080
 tail -f /dev/null
}
