#!/bin/ash

# Cache all of the data from the data directory

/bin/mkdir -p /mnt/volumes/container/stash
/bin/cp -rv /opt/uptime-kuma/data/* /mnt/volumes/container/stash/

# /usr/bin/sqlite3 /opt/uptime-kuma/data/kuma.db ".dump" | /bin/gzip -c > /mnt/volumes/container/kuma.gz
